name: Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  snake:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake (dark smooth)
        uses: Platane/snk@v3
        with:
          github_user_name: Harsh-Tiwari678
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-dark&color_snake=#00ff99&color_dots=#161b22,#0e4429,#006d32,#26a641,#39d353

      - name: Push to branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
